// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Text$ReactTemplate = require("./Text.bs.js");

var paragraph = "Hello this is absolutely a paragraph";

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Text$ReactTemplate.make(paragraph, /* array */[])), "index3");

exports.paragraph = paragraph;
/*  Not a pure module */
