// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Text");

function make(paragraph, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          tabIndex: 0,
                          onKeyPress: (function () {
                              return Curry._1(self[/* send */3], /* KeyDown */0);
                            })
                        }, React.createElement("p", undefined, React.createElement("span", undefined, self[/* state */1][/* beginning */1]), React.createElement("span", undefined, self[/* state */1][/* ending */2])), React.createElement("span", undefined, String(self[/* state */1][/* lettersCorrect */0])));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* lettersCorrect */0,
                      /* beginning */"",
                      /* ending */paragraph,
                      /* position */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (_, state) {
              return /* Update */Block.__(0, [/* record */[
                          /* lettersCorrect */state[/* lettersCorrect */0] + 1 | 0,
                          /* beginning */state[/* beginning */1],
                          /* ending */state[/* ending */2],
                          /* position */state[/* position */3]
                        ]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
